# Generated by Django 5.2.1 on 2025-05-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nr_of_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Drink', 'Drink'), ('Dessert', 'Dessert'), ('Appetizer', 'Appetizer'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
