# Generated by Django 5.2.1 on 2025-05-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='default_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
