# Generated by Django 5.2.1 on 2025-05-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0004_product_image_profile_avatar_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_link',
        ),
    ]
